language: cpp
compiler:
  - clang
  - g++

os:
  - linux
  - osx
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install visualstudio2017-workload-vctools -y; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then (cd ./test/external && ./build_gtest.sh); fi

script:
  # Windows
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./scripts/compile_cl.bat; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./scripts/run_tests.bat; fi
  # Darwin+Linux
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then STDVERSION=c++98 ./scripts/compile.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then STDVERSION=c++0x ./scripts/compile.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then STDVERSION=c++03 ./scripts/compile.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then STDVERSION=c++11 ./scripts/compile.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then STDVERSION=c++17 ./scripts/compile.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then STDVERSION=c++2a ./scripts/compile.sh; fi
  # the one we wish to run
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then STDVERSION=c++98 USE_ASAN=1 ./scripts/compile.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./scripts/run_tests.sh; fi
