language: cpp
compiler:
  - clang

os:
  - linux
  - osx
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install visualstudio2017-workload-vctools -y; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then (cd ./test/external && ./build_gtest.sh); fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./scripts/compile_cl.bat; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./scripts/run_tests.bat; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./scripts/compile_clang.sh; fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then ./scripts/run_tests.sh; fi
