#theme: jekyll-theme-slate
#remote_theme: Wiredcraft/carte
#remote_theme: pmarsceill/just-the-docs
remote_theme: chromatical/jekyll-materialdocs
#theme: just-the-docs

# Enable or disable the site search
search_enabled: false

# just-the-docs
#color_scheme: "dark"
# $body-text-color: $grey-dk-100;
# $body-heading-color: $grey-dk-300;
$link-color: $blue-000;
# $body-text-color: $grey-dk-000
# $body-heading-color: $grey-dk-300;

markdown: kramdown
highlighter: 'rouge'
syntax-highlighting:
  enabled : true
  css: /assets/css/monokai.css

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  # syntax_highlighter_opts:
  #   # Use existing pygments syntax highlighting css
  #   css_class: 'cobalt'


# site options for MaterialDocs (https://github.com/chromatical/jekyll-materialdocs)
# logo: /path/to/logo.png # an absolute or relative image path to use as the site logo
# mdl_colors: indigo-pink # a supported Material Design Lite color scheme
copyright: Mathias Westerdahl # will override the copyright notice (default is site title)
search: true # enabled by default, set to false to disable site search
# menu_style: dropdown # will only show child menu items for the main item selected

footer-links:
  github: JCash/jctest
  twitter: mwesterdahl76

baseurl: "/jctest"


# Use the following plug-ins
gems:
  - jekyll-remote-theme
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  #- just-the-docs