#theme: jekyll-theme-slate
remote_theme: Wiredcraft/carte

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
css_class: 'highlight'

footer-links:
  github: JCash/jctest
  twitter: mwesterdahl76

baseurl: "/jctest"


# Use the following plug-ins
gems:
- jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
