name: Build

on: [push, pull_request_target]

jobs:
  build-linux:
    strategy:
      matrix:
        feature: [NOFEATURE, USE_ASAN=1]
        compiler: [g++, clang++]
        arch:    ["-m64", "-m32"]
        platform: [c++0x, c++11, c++14, c++17, c++20, c++2b]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Install
      #   run: apt-get install -y gcc-multilib g++-multilib
      - name: Build tests
        run: CXX=${{ matrix.compiler }} STDVERSION=${{ matrix.platform }} ARCH=${{ matrix.arch }} ${{ matrix.feature }} ./scripts/compile.sh
      - name: Run Tests
        run: ./scripts/run_tests.sh

  build-macos:
    strategy:
      matrix:
        feature: [NOFEATURE, USE_ASAN=1]
        platform: [c++0x, c++11, c++14, c++17, c++20, c++2b]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build tests
        run: STDVERSION=${{ matrix.platform }} ${{ matrix.feature }} ./scripts/compile.sh
      - name: Run Tests
        run: ./scripts/run_tests.sh

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build tests
        run: ./scripts/compile_cl.bat
      - name: Run Tests
        run: ./scripts/run_tests.bat
