name: Build

on: [push, pull_request_target]

jobs:
  build-linux:
    strategy:
      matrix:
        feature: ["", "USE_ASAN=1"]
        compiler: [g++, clang++]
        arch:    ["-m64", "-m32"]
        platform: [c++0x, c++11, c++14, c++17, c++20, c++2b]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: sudo apt-get install -y gcc-multilib g++-multilib
      - name: Build tests
        run: CXX=${{ matrix.compiler }} STDVERSION=${{ matrix.platform }} ARCH=${{ matrix.arch }} ${{ matrix.feature }} ./scripts/compile.sh
      - name: Run Tests
        run: ./scripts/run_tests.sh

  build-macos:
    strategy:
      matrix:
        feature: ["", "USE_ASAN=1"]
        platform: [c++0x, c++11, c++14, c++17, c++20, c++2b]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build tests
        run: STDVERSION=${{ matrix.platform }} ${{ matrix.feature }} ./scripts/compile.sh
      - name: Run Tests
        run: ./scripts/run_tests.sh

  build-windows:
    strategy:
      matrix:
        arch:       [amd64, amd64_x86, amd64_arm64]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build tests
        run: ./scripts/compile_cl.bat
      - name: Run Tests
        run: ./scripts/run_tests.bat
